---
brew_formulae:
  - aiven-client
  - ansible
  - ansible-lint
  - aom
  - aribb24
  - asdf
  - atuin
  - awscli
  - bash
  - bat
  - bc
  - broot
  - brotli
  - btop
  - bun
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chafa
  - cjson
  - cmatrix
  - coreutils
  - cryptography
  - csvkit
  - dav1d
  - deno
  - docker
  - docker-completion
  - docker-compose
  - duti
  - eza
  - fd
  - ffmpeg
  - fish
  - flac
  - fontconfig
  - freetype
  - frei0r
  - fribidi
  - fselect
  - fzf
  - gawk
  - gdk-pixbuf
  - gemini-cli
  - gettext
  - gh
  - giflib
  - git
  - git-delta
  - git-filter-repo
  - gitleaks
  - glab
  - glib
  - gmp
  - gnu-sed
  - gnupg
  - gnutls
  - go
  - gpgme
  - gpgmepp
  - graphite2
  - harfbuzz
  - highway
  - htop
  - httpie
  - hyperfine
  - icu4c@77
  - icu4c@78
  - imagemagick
  - imath
  - ipython
  - jasper
  - jpeg-turbo
  - jpeg-xl
  - jq
  - k6
  - k9s
  - krb5
  - kubernetes-cli
  - kustomize
  - lame
  - lazydocker
  - lazygit
  - leptonica
  - lf
  - libarchive
  - libass
  - libassuan
  - libavif
  - libb2
  - libbluray
  - libde265
  - libdeflate
  - libevent
  - libgcrypt
  - libgit2
  - libgpg-error
  - libheif
  - libiconv
  - libidn2
  - libksba
  - liblinear
  - liblqr
  - libmicrohttpd
  - libnghttp2
  - libnghttp3
  - libngtcp2
  - libogg
  - libomp
  - libplacebo
  - libpng
  - libraw
  - librist
  - librsvg
  - libsamplerate
  - libsndfile
  - libsodium
  - libsoxr
  - libssh
  - libssh2
  - libtasn1
  - libtiff
  - libtool
  - libudfread
  - libultrahdr
  - libunibreak
  - libunistring
  - libusb
  - libuv
  - libvidstab
  - libvmaf
  - libvorbis
  - libvpx
  - libx11
  - libxau
  - libxcb
  - libxdmcp
  - libxext
  - libxrender
  - libyaml
  - libzip
  - little-cms2
  - lpeg
  - lua
  - luajit
  - luv
  - lz4
  - lzo
  - m4
  - mbedtls
  - mbedtls@3
  - minikube
  - molten-vk
  - mpdecimal
  - mpfr
  - mpg123
  - mpv
  - mujs
  - ncurses
  - neofetch
  - neovim
  - nerdfetch
  - nettle
  - nmap
  - node
  - npth
  - nspr
  - nss
  - oniguruma
  - opencore-amr
  - openexr
  - openjpeg
  - openjph
  - openssl@3
  - opus
  - p11-kit
  - pandoc
  - pango
  - parallel
  - pcre2
  - pinentry
  - pixman
  - poppler
  - popt
  - postgresql@17
  - procs
  - pycparser
  - python@3.13
  - python@3.14
  - qrencode
  - rav1e
  - readline
  - redis
  - ripgrep
  - ripgrep-all
  - rpds-py
  - rsync
  - rubberband
  - ruby
  - screenresolution
  - sdl2
  - shaderc
  - shared-mime-types
  - shuffledns
  - simdjson
  - snappy
  - speex
  - sqlite
  - srt
  - svt-av1
  - tailscale
  - tesseract
  - theora
  - tmux
  - tree
  - tree-sitter@0.25
  - trufflehog
  - uchardet
  - unbound
  - unibilium
  - utf8proc
  - uv
  - uvwasi
  - vapoursynth
  - vim
  - virtualenv
  - vulkan-headers
  - vulkan-loader
  - watch
  - webp
  - wget
  - x264
  - x265
  - xorgproto
  - xvid
  - xxhash
  - xz
  - yq
  - yt-dlp
  - zeromq
  - zimg
  - zoxide
  - zstd

brew_casks:
  - alt-tab
  - antigravity
  - arc
  - balenaetcher
  - burp-suite
  - calibre
  - claude
  - cursor
  - discord
  - font-commit-mono-nerd-font
  - font-fira-code
  - font-ibm-plex-mono
  - font-jetbrains-mono
  - font-jetbrains-mono-nerd-font
  - font-maple-mono
  - font-maple-mono-nf
  - font-symbols-only-nerd-font
  - ghostty
  - gimp
  - google-chrome
  - http-toolkit
  - iterm2
  - jordanbaird-ice
  - localsend
  - ngrok
  - obsidian
  - onlyoffice
  - paper
  - pearcleaner
  - postman
  - protonvpn
  - raycast
  - slack
  - spotify
  - stats
  - superwhisper
  - tailscale-app
  - telegram
  - visual-studio-code
  - zed
  - zen
