---
# VS Code extensions
vscode_extensions:
  - ahmadalli.vscode-nginx-conf
  - alefragnani.bookmarks
  - alefragnani.project-manager
  - anthropic.claude-code
  - astro-build.astro-vscode
  - bierner.emojisense
  - bierner.markdown-mermaid
  - christian-kohler.path-intellisense
  - cstrap.python-snippets
  - dbaeumer.vscode-eslint
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - foxundermoon.shell-format
  - github.copilot
  - github.copilot-chat
  - github.github-vscode-theme
  - github.vscode-pull-request-github
  - golang.go
  - google.gemini-cli-vscode-ide-companion
  - grammyjs.grammyjs
  - grapecity.gc-excelviewer
  - inferrinizzard.prettier-sql-vscode
  - ipedrazas.kubernetes-snippets
  - johnnymorganz.stylua
  - kevinrose.vsc-python-indent
  - mads-hartmann.bash-ide-vscode
  - malmaud.tmux
  - mechatroner.rainbow-csv
  - mgesbert.python-path
  - ms-azuretools.vscode-containers
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.black-formatter
  - ms-python.debugpy
  - ms-python.flake8
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-python.vscode-python-envs
  - ms-vscode.vscode-typescript-next
  - naumovs.color-highlight
  - njqdev.vscode-python-typehint
  - oderwat.indent-rainbow
  - pkief.material-icon-theme
  - redhat.ansible
  - redhat.vscode-yaml
  - sleistner.vscode-fileutils
  - subframe7536.custom-ui-style
  - sumneko.lua
  - uniquevision.vscode-plpgsql-lsp
  - upstash.context7-mcp
  - usernamehw.errorlens
  - vscodevim.vim
  - vspacecode.whichkey
  - yzhang.markdown-all-in-one

# Cursor extensions
cursor_extensions:
  - alefragnani.bookmarks
  - alefragnani.project-manager
  - anthropic.claude-code
  - astro-build.astro-vscode
  - bierner.markdown-mermaid
  - catppuccin.catppuccin-vsc
  - christian-kohler.path-intellisense
  - cstrap.python-snippets
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - github.github-vscode-theme
  - github.vscode-pull-request-github
  - golang.go
  - grapecity.gc-excelviewer
  - inferrinizzard.prettier-sql-vscode
  - ipedrazas.kubernetes-snippets
  - johnnymorganz.stylua
  - kevinrose.vsc-python-indent
  - mads-hartmann.bash-ide-vscode
  - mechatroner.rainbow-csv
  - mgesbert.python-path
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.black-formatter
  - ms-python.flake8
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-vscode.vscode-typescript-next
  - naumovs.color-highlight
  - njqdev.vscode-python-typehint
  - oderwat.indent-rainbow
  - pkief.material-icon-theme
  - redhat.vscode-yaml
  - sleistner.vscode-fileutils
  - subframe7536.custom-ui-style
  - sumneko.lua
  - usernamehw.errorlens
  - vscodevim.vim
  - vspacecode.whichkey
